-- AlterTable
ALTER TABLE "tickets" ALTER COLUMN "ticket_submitteddate" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "ticket_assigneddate" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "ticket_resolveddate" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "user_dob" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;
